name: mqtt_client
description: A server and browser based MQTT client for Dart supporting normal, secure sockets and websockets.
version: 9.0.0
homepage: https://github.com/shamblett/mqtt_client

environment:
 sdk: '>=2.12.0 <3.0.0'

dependencies:
 typed_data: '^1.1.6'
 event_bus: '^2.0.0'
 path: '^1.6.4'
 crypto: '^3.0.0-nullsafety.0'
 meta: '^1.3.0'

dev_dependencies:
 test: '^1.14.7'
 mockito: '^5.0.0-nullsafety.7'
 pedantic: '^1.9.0'
 pana: '^0.15.3'
 build_runner: '^1.11.1'
 build_test: '^1.3.6'
 build_web_compilers: '^2.16.3'





